UPSTREAM:PROTOCOL: ath12k: fix frame size warning of ath12k_sta_ml_reconfig_handler()
In ath12k_sta_ml_reconfig_handler(), peer_arg has been declared as local
variable which crosses the frame size of 1024 bytes, causing the below
warning

drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_sta_ml_reconfig_handler':
drivers/net/wireless/ath/ath12k/mac.c:14139:1: error: the frame size of 1040 bytes
is larger than 1024 bytes [-Werror=frame-larger-than=]

Fix the warning by allocating peer_arg dynamically.

Fixes: 130c58a593cb ("UPSTREAM:PROTOCOL: wifi: ath12k: add support for dynamic link addition and removal in AP MLD")

Patch-dependency: None

Change-Id: Idb778ee2940ed924018045c6d36aa29961a6058b
Signed-off-by: Karthikeyan Kathirvel <karthikeyan.kathirvel@oss.qualcomm.com>